AllCops:
  Exclude:
    - 'spec/spec_helper.rb'
    - 'chain_punk.gemspec'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/WordArray:
    Enabled: false
